services:
  traefik:
    image: traefik:v2.9
    ports:
      - "80:80"
      # Uncomment this line to enable the traefik dashboard
      # - "8080:8080"
      # Uncomment this line to enable HTTPS
      # - "443:443"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./dynamic.yml:/etc/traefik/dynamic.yml
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}

    networks:
      - traefik

  frontend:
    build: ./Frontend
    restart: always
    image: ghcr.io/uni-bremen-agst/see-manager-frontend:1.0.0
    depends_on:
      - backend
      - traefik
    networks:
      - traefik
      - default

  backend:
    privileged: true
    build: ./Backend
    image: ghcr.io/uni-bremen-agst/see-manager-backend:1.0.0
    restart: always
    depends_on:
      - traefik
    volumes:
      - backend-data:/see
      - ${DOCKER_HOST}:/var/run/docker.sock
    environment:
      # You should not change these values here.
      # Use the env file instead
      BACKEND_DOMAIN: ${DOMAIN_NAME}
      FRONTEND_DOMAIN: ${DOMAIN_NAME}
      FRONTEND_SCHEME: HTTP
      FILESTORAGE_DIR: /see/file-storage
      SQLITE_DB_FILE: /see/database.db
      # Docker daemon must be reachable from backend container to spawn game servers.
      DOCKER_HOST: unix:///var/run/docker.sock
      # This is the docker host's external IP or domain. Game servers will be reachable on this host.
      DOCKER_HOST_EXTERNAL: ${DOCKER_HOST_EXTERNAL}
      GAME_SERVER_IMAGE: ${DOCKER_IMAGE_NAME}
      # JWT settings
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      # This will add an admin account to the backend. Use with care!
      ADD_ADMIN_NAME: ${INITIAL_ADMIN_USERNAME}
      ADD_ADMIN_PASSWORD: ${INITIAL_ADMIN_PASSWORD}
    networks:
      - traefik
      - default

networks:
  traefik:
  default:


volumes:
  backend-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./backend-data
